# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'sqlite3',
        'hashlib',
        'datetime',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'tkcalendar',
        'babel',
        'babel.numbers',
        'components',
        'components.dialogs',
        'assets',
        'assets.styles',
        'utils',
        'utils.helpers',
        'database',
        'database.models',
        'database.database_manager',
        'controllers',
        'controllers.auth_controller',
        'controllers.product_controller',
        'controllers.customer_controller',
        'controllers.order_controller',
        'controllers.cart_controller',
        'views',
        'views.login_view',
        'views.signup_view',
        'views.admin_dashboard_view',
        'views.customer_dashboard_view',
        'views.products_view',
        'views.customers_view',
        'views.orders_view',
        'views.cart_view',
        'views.shop_view',
        'views.sales_view',
        'views.profile_view',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'pytest',
        'IPython',
        'jupyter',
        'notebook',
        'setuptools',
        'pip',
        'wheel',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GirlushCollections',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None
)
